name: CI Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 4️⃣ Build all modules
      - name: Build
        run: ./gradlew build --no-configuration-cache

      # 5️⃣ Run tests
      - name: Run tests
        run: ./gradlew test --no-configuration-cache