name: MaterializeKMP Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Publish to Maven Central
    runs-on: macos-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Read version from file
        id: version
        run: |
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2 | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish MaterializeKMP
        run: |
          ./gradlew clean publish \
            -Pversion=$VERSION \
            -PsigningEnabled=true \
            --stacktrace --info