name: Publish to Maven Central

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    environment: MAVEN

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print key ID (masked in logs)
        run: echo "Key ID is ${{ secrets.GPG_SIGNING_KEY_ID }}"
