name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Release library
    runs-on: macos-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Kotlin Native Cache
        uses: actions/cache@v3
        with:
          key: kotlin-native-${{ hashFiles('gradle.properties') }}
          path: ~/.konan

      - name: Read version from version.properties
        id: version
        run: |
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}

        run: ./gradlew publishToMavenCentral --no-configuration-cache