name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Release library
    runs-on: macos-latest
    continue-on-error: false

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup JDK 17
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 4. Cache Kotlin Native compiler
      - name: Kotlin Native Cache
        uses: actions/cache@v3
        with:
          key: kotlin-native-${{ hashFiles('gradle.properties') }}
          path: ~/.konan

      # 5. Read version from version.properties
      - name: Read version
        id: version
        run: |
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 6. Decode base64 GPG private key and export to Gradle property
      - name: Decode GPG key
        run: |
          echo "${{ secrets.GPG_KEY_CONTENTS }}" | base64 --decode > private.asc
          echo "ORG_GRADLE_PROJECT_signingInMemoryKey=$(cat private.asc)" >> $GITHUB_ENV

      # 7. Publish to Maven Central
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache