name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Extract Changelog for Release
        id: changelog
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          # Extract the changelog for the current version
          awk -v version="$VERSION" '
            $0 ~ "^## \\[" version "\\]" { in_section=1; next }
            $0 ~ "^## \\[" && in_section { exit }
            in_section && $0 != "---" && NF { print }
            ' CHANGELOG.md > extracted_changelog.md
          
          # Output the extracted changelog into GitHub Actions environment for later steps
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat extracted_changelog.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish to Sonatype
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ env.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
